applications/urls.py
from django.urls import path

from applications import views
app_name = "applications"

urlpatterns = [
    path("", views.list, name="list"),
    path("edit/<id>/", views.edit, name="edit")
]

fund/urls.py
from django.urls import path

from fund import views
app_name = "fund"

urlpatterns = [
    path("", views.list, name="list"),
    path("add", views.add_fund, name="add"),
    path("view/<id>/", views.view, name="view"),
]

fundings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("projects/", include("projects.urls")),
    path("applications/", include("applications.urls")),
    path("questions/", include("questions.urls")),
    path("fund/", include("fund.urls")),
    path("file-manager/", include("filemanager.urls")),
    path("", include("main.urls"))
]

applications/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
import os
from django.contrib.postgres.fields import ArrayField

from fund.models import FbFunding
from projects.models import FbProjects

FbUser = get_user_model()
APPLICATION_STATUS = (("not submitted", "Not Submitted"), )


class FbApplication(models.Model):
    project = models.ForeignKey(FbProjects, related_name="project_applications", on_delete=models.CASCADE)
    funding = models.ForeignKey(FbFunding, related_name="funding_applications", on_delete=models.CASCADE)
    request = models.ForeignKey(FbUser, related_name="my_approve_requests", on_delete=models.SET_NULL, null=True)
    username = models.CharField(max_length=255, null=True, blank=True)
    password = models.CharField(max_length=255, null=True, blank=True)
    comment = models.CharField(max_length=5000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=255, default="not submitted", null=True,
                              choices=APPLICATION_STATUS, blank=True)
    created_by = models.ForeignKey(FbUser, related_name="created_application", on_delete=models.CASCADE)

applications/forms.py
from django.forms import ModelForm

from applications import models


class FbApplicationForm(ModelForm):

    class Meta:
        model = models.FbApplication
        fields = "__all__"

applications/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from accounts.utils import generate_jwt
from applications.models import FbApplication
from fund.models import FbFunding
from questions.models import FbQuestions


def list(request):
    return redirect("projects:list")


@login_required
def edit(request, **kwargs):
    questions = FbQuestions.objects.all()
    application = get_object_or_404(FbApplication, pk=kwargs.get("id"))
    document = application.funding.document_id
    print(application.funding.document_id)
    token = generate_jwt(request.user, document)
    return render(request, "applications/edit-application.html", {"questions": questions,
                                                                  "document": document,
                                                                  "token": token, })

applications/templates/applications/edit-application.html
{% extends "main/base.html" %}
{% load static %}
{% load humanize %}

{% block pagecss %}
    <script src="http://localhost:5000/pspdfkit.js"></script>
        <link href="{% static 'main/plugins/gritter/css/jquery.gritter.css'%}" rel="stylesheet" />

{% endblock %}

{% block super_container %}
<div class="row">
    <div class="col-lg-3">
        <a href="{% url "applications:list" %}" class="btn btn-link">Go Back</a>
    </div>
    <div class="col-lg-9 text-right p-10">
    <a href="#modal-list-question"  class="btn btn-default m-r-5" data-toggle="modal">Question Bank</a>
        <a href="#modal-request-answer" class="btn btn-default m-r-5" data-toggle="modal">Request Answer</a>
    <a href="javascript:;" data-click="swal-success" class="btn btn-success m-r-5">Send for Review </a>

    </div>
</div>
<!-- 2. Element where PSPDFKit will be mounted. -->
<div id="pspdfkit" style="width: 100%; height: 100%;"></div>

<!-- 3. Initialize PSPDFKit. -->
<script>
    PSPDFKit.load({
        container: "#pspdfkit",
        documentId: "{{ document }}",
        authPayload: { jwt: "{{token}}" },
        instant: true
    })
        .then(function(instance) {
            console.log("PSPDFKit loaded", instance);
        })
        .catch(function(error) {
            console.error(error.message);
        });
</script>
<div class="modal fade" id="modal-list-question" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Question Bank</h4>
                <!--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>-->
            </div>
            <div class="modal-body">
                <div class="row m-b-40" >
                    <div class="col-lg-6">
                        <input type="email" class="form-control m-b-5" placeholder="Search for questions">
                    </div>

                </div>
                <div class="row">

                    <div class="col-lg-12">

                        <div class="panel panel-inverse" data-sortable-id="index-8">

                            <div class="panel-body p-0">
                                <table class="table table-valign-middle">
                                    <thead>

                                    </thead>
                                    <tbody>

                            {% for q in questions %}
                                <tr>
                                <td>
                                    <div>
                                        <div ><h6>{{ q.title }}</h6></div>
                                        <div class="m-t-5">
                                            {% for c in q.tag %}
                                                <span class="label label-success">{{ c }}</span>
                                            {% endfor %}

                                        </div>
                                    <p class="m-t-5">
                                        {{ q.answer }}
                                    </p>
                                    </div>
                                    <div class="m-t-5">
                                        <span class="m-r-10">Last Edit: <strong>{{ q.updated_at |naturaltime }}</strong></span>
                                        <span class="m-r-10">Created: <strong>{{ q.created_at | naturaltime }}</strong></span>
                                        <span class="m-r-10">Created By: <strong>{{ q.created_by.full_name }}</strong></span>
                                    </div>
                                </td>
                                <td>
                                    <a   data-clipboard-text="{{ q.answer }}" class=" copy btn btn-default m-r-5 m-b-5" >
                                                Copy Answer
                                                <i class="fa fa-fw  fa-fw fa-copy"></i>
                                            </a>
                                </td>
                            </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="4">No question added</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Close</a>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-request-answer" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Request Answer</h4>
                <!--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>-->
            </div>
            <div class="modal-body">
                <form>

                    <div class="form-group">
                        <label>User</label>
                        <select class="form-control">
                            <option>--Select User---</option>
                            <option>Cassie</option>
                            <option>Brandon</option>
                            <option>Jaxon</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <textarea class="form-control"></textarea>
                    </div>
                </form>

            </div>
            <div class="modal-footer">
                <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Close</a>
                <a href="javascript:;" class="btn btn-success" id="send" data-dismiss="modal">Send</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block pagejs %}

<!-- ================== BEGIN PAGE LEVEL JS ================== -->
<script src="{% static 'main/js/apps.min.js'%}"></script>
<script src="{% static 'main/plugins/gritter/js/jquery.gritter.js'%}"></script>
<script src="{% static 'main/plugins/bootstrap-sweetalert/sweetalert.min.js'%}"></script>
{#<script src="{% static 'main/js/demo/ui-modal-notification.demo.min.js'%}"></script>#}
<script src="{% static 'main/js/demo/ui-modal-notification.demo.min.js'%}"></script>
    <script src="{% static 'main/plugins/clipboard/clipboard.min.js' %}"></script>
	<script src="{% static 'main/js/demo/form-plugins.demo.js' %}"></script>
<!-- ================== END PAGE LEVEL JS ================== -->

<script>
    $(document).ready(function() {
        App.init();
        Notification.init();
        FormPlugins.init();

    });
</script>
{% endblock %}

applications/templates/applications/list.html
{% extends "main/base.html" %}
{% load static %}
{% load humanize %}

{% block pagecss %}
{% endblock %}

{% block content %}
<div id="content" class="content">
        <!-- begin breadcrumb -->
        <ol class="breadcrumb pull-right">
            <li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
            <li class="breadcrumb-item active">Funding Applications</li>
        </ol>
        <!-- end breadcrumb -->
        <!-- begin page-header -->
        <h1 class="page-header">{{ project.name }} Funding Applications </h1>
        <!-- end page-header -->
        <div class="row m-b-40" >
            <div class="col-lg-3">
                <input type="email" class="form-control m-b-5" placeholder="Search for questions">
            </div>
            <div class="col-lg-6">
                <div class="text-right">

                    <div class="btn-group m-r-5 m-b-5">
                        <a href="javascript:;" class="btn btn-default">Filter</a>
                        <a href="javascript:;" data-toggle="dropdown" class="btn btn-default dropdown-toggle" aria-expanded="false"></a>
                        <ul class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(86px, 34px, 0px); top: 0px; left: 0px; will-change: transform;">
                            <li><a href="javascript:;">Most Recent</a></li>
                            <li><a href="javascript:;">Category</a></li>
                        </ul>
                    </div>
                    <a href="#modal-new" class="btn btn-primary" data-toggle="modal">Add New</a>
                </div>
            </div>
        </div>
        <div class="row">

            <div class="col-lg-9">

                <div class="panel panel-inverse" data-sortable-id="index-8">

                    <div class="panel-body p-0">
                        <table class="table table-valign-middle">
                            <thead>
                                <th>Project</th>
                                <th>Fund Name</th>
                                <th>Status</th>
                                <th>Created</th>
                                <th></th>
                            </thead>
                            <tbody>

                            {% for app in applications %}
                                <tr>
                                <td>{{ app.project.name }}</td>
                                <td>{{ app.funding.fund_name }}</td>
                                <td>{{ app.status }}</td>
                                <td>{{ app.created_at|naturalday  }}</td>
                                <td>
                                    <!--<button class="btn btn-danger m-r-5 m-b-5">-->
                                    <!--Delete-->
                                    <!--<i class="fa fa-fw  fa-trash-alt"></i>-->
                                    <!--</button>-->
                                    <a href="{% url 'applications:edit' id=app.id %}"
                                       class="btn btn-default m-r-5 m-b-5" >
                                        View <i class="fa fa-fw  fa-eye"></i>
                                    </a>
{#                                    <a href="#modal-edit" class="btn btn-default m-r-5 m-b-5" data-toggle="modal">#}
{#                                        View <i class="fa fa-fw  fa-eye"></i>#}
{#                                    </a>#}
                                </td>
                            </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="4">No application for the project</td>
                                </tr>
                            {% endfor %}



                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div>
    <!-- end #content -->
    <div class="modal fade" id="modal-new" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <form method="post" action="">
                    {% csrf_token %}
                <div class="modal-header">
                    <h4 class="modal-title">New Application</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">
{#                        <div class="form-group">#}
{#                            <label>Project</label>#}
{#                            <select class="form-control">#}
{#                                <option>--Select Project---</option>#}
{#                                <option>Project 1</option>#}
{#                                <option>Project 2</option>#}
{#                            </select>#}
{#                        </div>#}
                        <div class="form-group">
                            <label>Fund Name</label>
                            <select class="form-control" name="funding" value="{{ form.funding.value }}">
                                <option>--Select Fund Name---</option>
                                {% for f in funding %}
                                    <option value="{{ f.id }}">{{ f.fund_name }} - {{ f.agency }}</option>
                                {% endfor %}

                            </select>
                        </div>
                        <div class="form-group">
                            <label>You approves the application?</label>
                            <select class="form-control" name="request" value="{{ form.request.value }}">
                                <option>--Select User---</option>
                                {% for u in users %}
                                     <option value="{{ u.uuid }}" >{{ u.full_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Application Portal Username</label>
                            <input class="form-control" type="text" placeholder="" name="username" value="{{ form.username.value }}"/>
                        </div>
                        <div class="form-group">
                            <label>Application Portal Password</label>
                            <input class="form-control" type="text" placeholder="" value="{{ form.password.value }}" name="password"/>
                        </div>
                        <div class="form-group">
                            <label>Comment</label>
                            <textarea class="form-control" name="comment">{{ form.username.value }}</textarea>
                        </div>


                </div>
                <div class="modal-footer">
                    <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Close</a>
                    <button type="submit" class="btn btn-danger">Save</button>
                </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal-edit" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <h4 class="modal-title">Newton Road Construction Application</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">

                        <div class="form-group">
                            <label>Project</label>
                            Newton Road Construction
                        </div>
                        <div class="form-group">
                            <label>Fund Name</label>
                            Provincial Road Construction Fund
                        </div>
                        <div class="form-group">
                            <label>You approves the application?</label>
                            Cassie James
                        </div>
                        <div class="form-group">
                            <label>Application Portal Username</label>
                            test
                        </div>
                        <div class="form-group">
                            <label>Application Portal  Password</label>
                            test
                        </div>
                        <div class="form-group">
                            <label>Comment</label>
                            <p>
                                Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
                                Donec ullamcorper nulla non metus auctor fringilla.
                            </p>

                        </div>

                </div>
                <div class="modal-footer">
                    <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Close</a>
                    <a href="{% url 'applications:edit' id="fdfd" %}" class="btn btn-danger">Edit</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{#{% block pagejs %}#}
{##}
{#{% endblock %}#}