accounts/urls.py
from django.urls import path, include, re_path
from rest_framework.routers import DefaultRouter

from accounts import views
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token
from accounts import api

app_name = "accounts"

# bank = DefaultRouter()
# bank.register(r"", api.IbLinkedBankAccountViewset, "banks")

urlpatterns = [

    path("signup/", views.signup, name="signup"),
    path("staff/", views.staff, name="staff"),
    path("signup/activate-email", views.activate_email, name="activate_email"),
    path("login-redirect/", views.login_redirect, name="login_redirect"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("post-logout/", views.post_logout_redirect, name="post-logout"),
    path("password/change/", views.password_change, name="change_password"),
    # path("password/set/", views.password_set, name="set_password"),
    path("password/reset/", views.password_reset, name="reset_password"),
    path("password/reset/done/", views.password_reset_done, name="reset_password_done"),
    path("password/reset/key/done/", views.password_reset_from_key_done, name="reset_password_from_key_done"),
    # path("password/reset/key/<uidb36>-<key>/", views.password_reset_from_key, name="reset_password_from_key"),
    re_path(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$", views.password_reset_from_key,
            name="reset_password_from_key"),
    path("confirm-email/<key>/", views.confirm_email, name="confirm_email"),
    re_path(r'^rest-auth/', include('rest_auth.urls')),
    re_path(r'^rest-auth/signup/', include('rest_auth.registration.urls')),
    path('jwt/api-token-auth/', obtain_jwt_token),
    path('jwt/api-token-refresh/', refresh_jwt_token),
    path('jwt/api-token-verify/', verify_jwt_token),
    path("resend-confirm-email/", api.WsResendActivationEmailAPIView.as_view(), name="resend_account_confirm"),

    # path('api/v1/get-profile/', api.IbGetProfileAPIView.as_view()),
    # path('api/v1/edit-profile/', api.IbGetProfileAPIView.as_view()),
    # # path('api/v1/search-users', api.IbUserSearchAPIView.as_view()),

    # path("", include('allauth.urls')),
]

filemanager/urls.py
from django.urls import path
from filemanager import views

app_name = "filemanager"

urlpatterns = [
    path("files", views.files, name="files")
]

fund/urls.py
from django.urls import path

from fund import views
app_name = "fund"

urlpatterns = [
    path("", views.list, name="list"),
    path("add", views.add_fund, name="add"),
    path("view/<id>/", views.view, name="view"),
]

fundings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("projects/", include("projects.urls")),
    path("applications/", include("applications.urls")),
    path("questions/", include("questions.urls")),
    path("fund/", include("fund.urls")),
    path("file-manager/", include("filemanager.urls")),
    path("", include("main.urls"))
]

main/urls.py
from django.urls import path

app_name = "main"
from main import views

urlpatterns = [
    path("",  views.index, name="home"),
    path("dashboard",  views.dashboard, name="dashboard")
]

projects/urls.py
from django.urls import path

from projects import views
app_name = "projects"

urlpatterns = [
    path("", views.list, name="list"),
    path("milestones/<id>/", views.milestone, name="milestone"),
    path("applications/<id>/", views.application, name="applications"),
    path("tasks", views.tasks, name="tasks")
]

questions/urls.py
from django.urls import path

from questions import views
app_name = "questions"

urlpatterns = [
    path("", views.list, name="list")
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, redirect


# Create your views here.
from django.urls import reverse_lazy


def index(request):

    return redirect(reverse_lazy("accounts:login"))

def dashboard(request):

    return render(request, "main/dashboard.html")

main/templates/main/partials/header.html
{% load static %}
<div id="header" class="header navbar-default">
			<!-- begin navbar-header -->
			<div class="navbar-header">
				<a href="{% url 'main:dashboard' %}" class="navbar-brand"><span class="navbar-logo"></span> <b>Fund</b>Box</a>
				<button type="button" class="navbar-toggle" data-click="sidebar-toggled">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<!-- end navbar-header -->

			<!-- begin header-nav -->
			<ul class="navbar-nav navbar-right">
				<!--<li>-->
					<!--<form class="navbar-form">-->
						<!--<div class="form-group">-->
							<!--<input type="text" class="form-control" placeholder="Enter keyword" />-->
							<!--<button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>-->
						<!--</div>-->
					<!--</form>-->
				<!--</li>-->
				<li class="dropdown">
					<a href="javascript:;" data-toggle="dropdown" class="dropdown-toggle f-s-14">
						<i class="fa fa-bell"></i>
						<span class="label">5</span>
					</a>
					<ul class="dropdown-menu media-list dropdown-menu-right">
						<li class="dropdown-header">NOTIFICATIONS (5)</li>
						<li class="media">
							<a href="javascript:;">
								<div class="media-left">
									<i class="fa fa-bug media-object bg-silver-darker"></i>
								</div>
								<div class="media-body">
									<h6 class="media-heading">Server Error Reports <i class="fa fa-exclamation-circle text-danger"></i></h6>
									<div class="text-muted f-s-11">3 minutes ago</div>
								</div>
							</a>
						</li>
						<li class="media">
							<a href="javascript:;">
								<div class="media-left">
									<img src="{% static 'main/img/user/user-1.jpg' %}" class="media-object" alt="" />
									<i class="fab fa-facebook-messenger text-primary media-object-icon"></i>
								</div>
								<div class="media-body">
									<h6 class="media-heading">Jeremy Schwartz</h6>
									<p>Quisque pulvinar tellus sit amet sem scelerisque tincidunt.</p>
									<div class="text-muted f-s-11">25 minutes ago</div>
								</div>
							</a>
						</li>
						<li class="media">
							<a href="javascript:;">
								<div class="media-left">
									<img src="{% static 'main/img/user/user-2.jpg' %}" class="media-object" alt="" />
									<i class="fab fa-facebook-messenger text-primary media-object-icon"></i>
								</div>
								<div class="media-body">
									<h6 class="media-heading">Olivia</h6>
									<p>Quisque pulvinar tellus sit amet sem scelerisque tincidunt.</p>
									<div class="text-muted f-s-11">35 minutes ago</div>
								</div>
							</a>
						</li>
						<li class="media">
							<a href="javascript:;">
								<div class="media-left">
									<i class="fa fa-plus media-object bg-silver-darker"></i>
								</div>
								<div class="media-body">
									<h6 class="media-heading"> New User Registered</h6>
									<div class="text-muted f-s-11">1 hour ago</div>
								</div>
							</a>
						</li>
						<li class="media">
							<a href="javascript:;">
								<div class="media-left">
									<i class="fa fa-envelope media-object bg-silver-darker"></i>
									<i class="fab fa-google text-warning media-object-icon f-s-14"></i>
								</div>
								<div class="media-body">
									<h6 class="media-heading"> New Email From John</h6>
									<div class="text-muted f-s-11">2 hour ago</div>
								</div>
							</a>
						</li>
						<li class="dropdown-footer text-center">
							<a href="javascript:;">View more</a>
						</li>
					</ul>
				</li>
				<li class="dropdown navbar-user">
					<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
						<img src="{% static 'main/img/user/user-13.jpg' %}" alt="" />
						<span class="d-none d-md-inline">Jeremy Schwartz</span> <b class="caret"></b>
					</a>
					<div class="dropdown-menu dropdown-menu-right">
						<a href="javascript:;" class="dropdown-item">Edit Profile</a>
						<!--<a href="javascript:;" class="dropdown-item"><span class="badge badge-danger pull-right">2</span> Inbox</a>-->
						<a href="javascript:;" class="dropdown-item">Calendar</a>
						<a href="javascript:;" class="dropdown-item">Setting</a>
						<div class="dropdown-divider"></div>
						<a href="javascript:;" class="dropdown-item">Log Out</a>
					</div>
				</li>
			</ul>
			<!-- end header navigation right -->
		</div>

main/templates/main/partials/nav.html
{%  load static  %}
<div id="sidebar" class="sidebar">
			<!-- begin sidebar scrollbar -->
			<div data-scrollbar="true" data-height="100%">
				<!-- begin sidebar user -->
				<ul class="nav">
					<li class="nav-profile">
						<a href="javascript:;" data-toggle="nav-profile">
							<div class="cover with-shadow"></div>
							<div class="image">
								<img src="{% static 'main/img/user/user-13.jpg' %}" alt="" />
							</div>
							<div class="info">
								Jeremy Schwartz
								<small>Economic Dev Officer</small>
							</div>
						</a>
					</li>

				</ul>
				<!-- end sidebar user -->
				<!-- begin sidebar nav -->

<ul class="nav">
					<li class="nav-header">Navigation</li>
					<li class="has-sub active">
						<a href="{% url 'main:dashboard' %}">
						    <i class="fa fa-th-large"></i>
						    <span>Dashboard</span>
					    </a>
					</li>

					<li class="has-sub active">
						<a href="{% url 'projects:list' %}">
							<i class="fa fa-lightbulb"></i>
							<span>Projects</span>
						</a>
					</li>
					<li class="has-sub active">
						<a href="{% url 'fund:list' %}">
							<i class="fa fa-dollar-sign"></i>
							<span>Funding</span>
						</a>
					</li>
					<li class="has-sub active">
						<a href="{% url 'applications:list' %}">
							<i class="fa fa-pencil-alt"></i>
							<span>Application</span>
						</a>
					</li>
					<li class="has-sub active">
						<a href="{% url 'questions:list' %}">
							<i class="fa fa-question"></i>
							<span>Question Bank</span>
						</a>
					</li>
                    <li class="has-sub active">
						<a href="{% url 'projects:tasks' %}">
							<i class="fa fa-tasks"></i>
							<span>My Task</span>
						</a>
					</li>
					<li class="has-sub active">
						<a href="{% url 'accounts:staff' %}">
							<i class="fa fa-users"></i>
							<span>Staff</span>
						</a>
					</li>
					<li class="has-sub active">
						<a href="{% url 'filemanager:files' %}">

							<i class="fa fa-book"></i>
							<span>File Manager</span>
						</a>
					</li>

				</ul>
				<!-- end sidebar nav -->
			</div>
			<!-- end sidebar scrollbar -->
		</div>
<div class="sidebar-bg"></div>