fund/urls.py
from django.urls import path

from fund import views
app_name = "fund"

urlpatterns = [
    path("", views.list, name="list"),
    path("add", views.add_fund, name="add"),
    path("view/<id>/", views.view, name="view"),
]

fundings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("projects/", include("projects.urls")),
    path("applications/", include("applications.urls")),
    path("questions/", include("questions.urls")),
    path("fund/", include("fund.urls")),
    path("file-manager/", include("filemanager.urls")),
    path("", include("main.urls"))
]

fund/models.py
import os

from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import ArrayField
from django.db import models

# Create your models here.
from django.utils import timezone

FbUser = get_user_model()


def doc_upload_path(instance, filename):
    filename, ext = os.path.splitext(filename)
    filename = "{0}{1}".format(int(timezone.now().timestamp()), ext)
    return "funding/upload/{0}".format(filename)


class FbFunding(models.Model):
    agency = models.CharField(max_length=255)
    fund_name = models.CharField(max_length=255)
    web_link = models.CharField(max_length=255, null=True)
    opening_date = models.DateField()
    closing_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    occurrence = models.CharField(max_length=255)
    occurrence_no = models.PositiveIntegerField(null=True)
    amount = models.FloatField(null=True)
    qualifiers = models.TextField(null=True)
    key_contacts = models.TextField(null=True)
    created_by = models.ForeignKey(FbUser, related_name="created_funds", on_delete=models.CASCADE, null=True)

    requirements = models.TextField(null=True)
    file = models.FileField(upload_to=doc_upload_path, null=True)
    document_id = models.CharField(max_length=255, null=True)
    categories = ArrayField(base_field=models.CharField(max_length=255))

fund/forms.py
import requests
from django.conf import settings
from django.db import transaction
from django.forms import ModelForm
from fund import models


class FbFundForm(ModelForm):

    class Meta:
        model = models.FbFunding
        fields = ["opening_date", "closing_date", "qualifiers", "fund_name", "agency",
                  "requirements", "key_contacts", "occurrence", "occurrence_no", "amount", "file", "categories"]

    def save(self, commit=True):
        with transaction.atomic():
            print(self.cleaned_data.get("file"), )
            file = {'file': (self.cleaned_data.get("file").name, self.cleaned_data.get("file"), "application/pdf")}

            respond = requests.post(settings.PSPDF_SERVER,
                                    files=file,
                                    headers={"Content-Type": "application/pdf",
                                             "Authorization": "Token token="+settings.PSPDF_AUTH_TOKEN})

            self.instance.document_id = respond.json().get("data").get("document_id")
            self.instance.save()
            return self.instance

fund/views.py
from django.shortcuts import render, redirect
from fund import models
# Create your views here.
from fund.forms import FbFundForm


def list(request):
    funds = models.FbFunding.objects.all()

    return render(request, "fund/list.html", context={"funds": funds})

def add_fund(request):
    form = FbFundForm(request.POST, request.FILES)
    if request.method == "POST":
        print(request.POST)
        print(form.errors, "jkfjsdfjdksfksn")
        if form.is_valid():
            form.save()
            return redirect("fund:list")
    return render(request, "fund/add-fund.html", context={"form": form})

def view(request, **kwargs):
    fund = models.FbFunding.objects.get(pk=kwargs.get("id"))
    return render(request, "fund/details.html", context={"fund": fund})

fund/templates/fund/add-fund.html
{% extends "main/base.html" %}
{% load static %}

{% block pagecss %}
{% endblock %}

{% block content %}
<div id="content" class="content">
        <!-- begin breadcrumb -->
        <ol class="breadcrumb pull-right">
            <li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
            <li class="breadcrumb-item active">Funding</li>
        </ol>
        <!-- end breadcrumb -->
        <!-- begin page-header -->
        <h1 class="page-header">Add New Funding </h1>
        <!-- end page-header -->

        <div class="row m-b-40">
            <div class="col-lg-10 panel panel-inverse" data-sortable-id="index-8">
                <div class="">
                    <div class="panel-body p-t-10">
                        {{ form.non_field_errors }}
                    <form action="{% url "fund:add" %}" method="post" enctype="multipart/form-data">
                        {%  csrf_token %}
                        <div class="row row-space-10">
                                <div class="col-md-6">
                                <div class="form-group m-b-10">
                                    <label>Funding Agency</label>
                                    <input class="form-control" name="agency"
                                           value = "{{ form.agency.value }}"
                                           type="text" placeholder="Funding Agency">
                                </div>
                                <div class="form-group m-b-10">
                                    <label>Fund Name</label>
                                    <input class="form-control"
                                           value = "{{ form.fund_name.value }}"
                                           name="fund_name" type="text" placeholder="Fund Name">
                                </div>
                                <div class="form-group m-b-10">
                                    <label>Web Link</label>
                                    <input class="form-control"
                                           value ="{{ form.web_link.value }}"
                                           name="web_link" type="url" placeholder="Web link">
                                </div>
                                <div class="form-group m-b-10">
                                    <label>Opening Date</label>
                                    <input class="form-control"
                                           value = "{{ form.opening_date.value }}"
                                           name="opening_date" type="date" placeholder="Opening Date">
                                </div>
                                <div class="form-group m-b-10">
                                    <label>Closing Date</label>
                                    <input class="form-control"
                                           value = "{{ form.closing_date.value }}"
                                           name="closing_date" type="date" placeholder="Closing Date">
                                </div>
                                <div class="form-group m-b-10">
                                    <label>Amount</label>
                                    <input class="form-control"
                                           value = "{{ form.amount.value }}"
                                           name="amount" type="tel" placeholder="Amount">
                                </div>
                                <div class="form-group m-b-10">
                                    <label class="form-check-label" > Re-occurrence </label>
                                    <select class="form-control"
                                            value = "{{ form.occurrence.value }}"
                                            name="occurrence">
                                        <option>Month</option>
                                        <option>Year</option>
                                    </select>
                                </div>
                                 <div class="form-group m-b-10">
                                    <label class="form-check-label" > Occurrence Frequency </label>
                                    <input class="form-control"
                                           value = "{{ form.occurrence_no.value }}"
                                           type="tel" placeholder="" name="occurrence_no">
                                </div>

                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Key Contacts</label>
                                    <textarea class="form-control"
                                              rows="3" name="key_contacts">{{ form.key_contacts.value }}</textarea>
                                </div>
                                <div class="form-group">
                                    <label>Qualifiers</label>
                                    <textarea class="form-control" rows="3"
                                              name="qualifiers">{{ form.qualifiers.value }}</textarea>
                                </div>
                                <div class="form-group">
                                    <label>Contribution Requirements</label>
                                    <textarea class="form-control" rows="3"
                                              name="requirements">{{ form.requirements.value }}</textarea>
                                </div>
                                <div class="form-group">
                                    <label>Categories</label>
                                    <textarea class="form-control" rows="3"
                                              name="categories">{{ form.categories.value }}</textarea>
                                </div>
                                <div>
                                    <label>Uploading supporting document </label>
                                    <input class="form-control" type="file" name="file">
                                </div>
                            </div>
                            <div class="m-t-15 pull-right" style="width: 100%">
                                <button type="submit" class="btn btn-sm btn-primary m-r-5">Save</button>
                                <a href="{% url "fund:list" %}" class="btn btn-sm btn-default">Cancel</a>
                            </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>


        </div>
        <!-- end row -->
    </div>
{% endblock %}

{#{% block pagejs %}#}
{##}
{#{% endblock %}#}

fund/templates/fund/details.html
{% extends "main/base.html" %}
{% load static %}
{% load humanize %}

{% block pagecss %}
{% endblock %}

{% block content %}
<div id="content" class="content">
        <!-- begin breadcrumb -->
        <ol class="breadcrumb pull-right">
            <li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
            <li class="breadcrumb-item active">Funding</li>
        </ol>
        <!-- end breadcrumb -->
        <!-- begin page-header -->
        <h1 class="page-header">Details </h1>
        <!-- end page-header -->

        <div class="row m-b-40">
            <div class="col-lg-10 panel panel-inverse" data-sortable-id="index-8">
                <div class="p-10">
                    <h2>{{ fund.fund_name }}</h2>
                    <div><small>{{ fund.agency }}</small>
                        <a href="{{ fund.web_link }}">Visit Website</a>
                    </div>
                    <div class="m-t-10">
                        <strong>Amount: </strong> ${{ fund.amount | intcomma }}
                    </div>
                    <div  class="m-t-15" >
                        <strong>Categories: </strong>
                    </div>
                    <div class="m-b-3 m-t-3">
                        {% for c in fund.categories %}
                            <span class="label label-inverse">{{ c }}</span>
                        {% endfor %}

                    </div>

                    <div class="m-t-15">
                        <span class="m-r-10"><label>Opening Date:</label> {{ fund.opening_date|date:"m-d-Y" }}</span>
                        <label>Closing Date:</label> {{ fund.closing_date|date:"m-d-Y" }}
                    </div>
                    <div class="m-t-15">
                        <h3>Key Contact</h3>
                        <div>
                            {{ fund.key_contacts }}
                        </div>
                    </div>
                    <div class="m-t-15">
                            <h3>Qualifiers</h3>
                        <p>
                            {{ fund.qualifiers }}
                        </p>
                    </div>
                    <div class="m-t-15">
                        <h3>Contribution Requirements</h3>
                        <p>
                            {{ fund.requirements }}
                        </p>
                    </div>
                    <div class="m-t-15">
                        <h3>Files Uploaded</h3>
                        <ul>
                            <li>{{ fund.file.name }} <a href="{{ fund.file.url }}" class="btn btn-link m-b-5">Download</a></li>

                        </ul>
                    </div>
                </div>
            </div>


        </div>
        <!-- end row -->
    </div>
{% endblock %}

{#{% block pagejs %}#}
{##}
{#{% endblock %}#}

fund/templates/fund/list.html
{% extends "main/base.html" %}
{% load static %}
{% load humanize %}


{% block pagecss %}
{% endblock %}

{% block content %}
<div id="content" class="content">
        <!-- begin breadcrumb -->
        <ol class="breadcrumb pull-right">
            <li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
            <li class="breadcrumb-item active">Funding</li>
        </ol>
        <!-- end breadcrumb -->
        <!-- begin page-header -->
        <h1 class="page-header">Funding </h1>
        <!-- end page-header -->
        <div class="row m-b-40" >
            <div class="col-lg-3">
                <input type="email" class="form-control m-b-5" placeholder="Search fund">
            </div>
            <div class="col-lg-6">
                <div class="text-right">

                    <div class="btn-group m-r-5 m-b-5">
                        <a href="javascript:;" class="btn btn-default">Filter</a>
                        <a href="javascript:;" data-toggle="dropdown" class="btn btn-default dropdown-toggle" aria-expanded="false"></a>
                        <ul class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(86px, 34px, 0px); top: 0px; left: 0px; will-change: transform;">
                            <li><a href="javascript:;">Most Recent</a></li>
                            <li><a href="javascript:;">Category</a></li>
                        </ul>
                    </div>
                    <a href="{% url "fund:add"  %}" class="btn btn-primary">Add New</a>
                </div>
            </div>
        </div>
        <div class="row">

            <div class="col-lg-9">

                <div class="panel panel-inverse" data-sortable-id="index-8">

                    <div class="panel-body p-0">
                        <table class="table table-valign-middle">
                            <thead>
                            <tr>
                                <th>Funding Agency</th>
                                <th>Amount</th>
                                <th>Start Date</th>
                                <th>Closing Date</th>
                                <!--<th>Status</th>-->

                            </tr>
                            </thead>
                            <tbody>
                            {%  for fund in funds %}
                            <tr>
                                <td><a href="{% url "fund:view"  id=fund.id %}">{{ fund.agency }}</a></td>
                                <td>${{ fund.amount |intcomma}}</td>
                                <td>{{ fund.opening_date |  date:"m-d-Y" }}</td>
                                <td>{{ fund.closing_date | date:"m-d-Y" }}</td>
                            </tr>
                            {%  endfor %}


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div>
{% endblock %}

{#{% block pagejs %}#}
{##}
{#{% endblock %}#}