fund/urls.py
from django.urls import path

from fund import views
app_name = "fund"

urlpatterns = [
    path("", views.list, name="list"),
    path("add", views.add_fund, name="add"),
    path("view/<id>/", views.view, name="view"),
]

fundings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("projects/", include("projects.urls")),
    path("applications/", include("applications.urls")),
    path("questions/", include("questions.urls")),
    path("fund/", include("fund.urls")),
    path("file-manager/", include("filemanager.urls")),
    path("", include("main.urls"))
]

projects/urls.py
from django.urls import path

from projects import views
app_name = "projects"

urlpatterns = [
    path("", views.list, name="list"),
    path("milestones/<id>/", views.milestone, name="milestone"),
    path("applications/<id>/", views.application, name="applications"),
    path("tasks", views.tasks, name="tasks")
]

projects/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
import os

from django.contrib.postgres.fields import ArrayField

# Create your models here.
from django.utils import timezone

from fund.models import FbFunding

FbUser = get_user_model()

def doc_upload_path(instance, filename):
    filename, ext = os.path.splitext(filename)
    filename = "{0}{1}".format(int(timezone.now().timestamp()), ext)
    return "projects/upload/{0}".format(filename)


class FbProjects(models.Model):
    name = models.CharField(max_length=255)
    category = models.CharField(max_length=255, null=True)
    start_date = models.DateField()
    end_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    funding = models.ManyToManyField(FbFunding, related_name="project_funding")
    created_by = models.ForeignKey(FbUser, related_name="created_projects", on_delete=models.CASCADE)
    description = models.TextField()
    budget = models.FloatField(null=True)
    file = models.FileField(upload_to=doc_upload_path, null=True, blank=True)
    # status = models.CharField(max_length=255, default="Not Submitted")
    # categories = ArrayField(base_field=models.CharField(max_length=255))


class FbMileStones(models.Model):
    name = models.CharField(max_length=255)
    due_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    project = models.ForeignKey(FbFunding, related_name="project_milestones", on_delete=models.CASCADE)
    created_by = models.ForeignKey(FbUser, related_name="created_milestone", on_delete=models.CASCADE)
    assignee = models.ForeignKey(FbUser, related_name="assigned_milestones", on_delete=models.CASCADE)
    description = models.TextField()
    reminder = models.PositiveIntegerField()
    file = models.FileField(upload_to=doc_upload_path, null=True, blank=True)

projects/forms.py
from django.forms import ModelForm

from projects.models import FbProjects, FbMileStones


class FbProjectForm(ModelForm):

    class Meta:
        model = FbProjects
        fields ="__all__"


class FbMileStonesForm(ModelForm):

    class Meta:
        model = FbMileStones
        fields ="__all__"

projects/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

# Create your views here.
from applications.forms import FbApplicationForm
from applications.models import FbApplication
from fund.models import FbFunding
from projects.forms import FbProjectForm, FbMileStonesForm
from projects.models import FbProjects, FbMileStones

FbUser = get_user_model()

@login_required
def list(request):
    form = FbProjectForm()
    funding = FbFunding.objects.all()
    projects = FbProjects.objects.all()
    milestones = FbMileStones.objects.all()
    print(request.user)
    if request.method == "POST":
        data = request.POST.copy()
        data["created_by"] = request.user.uuid
        form = FbProjectForm(data, request.FILES)
        if form.is_valid():
            print(form.errors)
            data = request.POST

            form.save()

            return redirect("projects:list")
        print(form.errors)
    return render(request, "projects/list.html", context={"form": form,
                                                          "milestones": milestones,
                                                          "projects": projects,
                                                          "funding": funding})

@login_required()
def milestone(request, **kwargs):
    form = FbMileStonesForm(initial={})
    milestones = FbMileStones.objects.filter(project=kwargs.get('id'))
    project = FbProjects.objects.get(pk=kwargs.get("id"))
    users = FbUser.objects.all()
    if request.method == "POST":
        data = request.POST.copy()
        data["created_by"] = request.user.uuid
        data["project"] = project.id
        form = FbMileStonesForm(data, request.FILES)
        if form.is_valid():
            print(form.errors)

            form.save()

            form = FbProjectForm()
        print(form.errors)
    return render(request, "projects/milestones.html", {"milestones": milestones,
                                                        "form": form,
                                                        "users": users,
                                                        "project": project})


@login_required()
def tasks(request):
    return render(request, "projects/tasks.html")


@login_required()
def application(request, **kwargs):
    form = FbApplicationForm(initial={})
    project = FbProjects.objects.get(pk=kwargs.get("id"))
    applications = FbApplication.objects.filter(project=kwargs.get("id"))
    funding = project.funding.all()
    users = FbUser.objects.all()
    if request.method == "POST":
        data = request.POST.copy()
        data["created_by"] = request.user.uuid
        data["project"] = project.id
        form = FbApplicationForm(data, request.FILES)
        if form.is_valid():
            print(form.errors)

            form.save()

            form = FbApplicationForm()
        print(form.errors)
    return render(request, "applications/list.html", {"form": form,
                                                      "users": users,
                                                      "project": project,
                                                      "applications": applications, "funding": funding})

projects/templates/projects/list.html
{% extends "main/base.html" %}
{% load static %}
{% load humanize %}
{% block pagecss %}
    <link href="../assets/plugins/jquery-jvectormap/jquery-jvectormap.css" rel="stylesheet" />
    <link href="../assets/plugins/bootstrap-datepicker/css/bootstrap-datepicker.css" rel="stylesheet" />
    <link href="../assets/plugins/gritter/css/jquery.gritter.css" rel="stylesheet" />
{% endblock %}

{% block content %}
<div id="content" class="content">
        <!-- begin breadcrumb -->
        <ol class="breadcrumb pull-right">
            <li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
            <li class="breadcrumb-item active">Projects</li>
        </ol>
        <!-- end breadcrumb -->
        <!-- begin page-header -->
        <h1 class="page-header">Projects</h1>
        <!-- end page-header -->
        <div class="row m-b-40" >
            <div class="col-lg-3">
                <input type="email" class="form-control m-b-5" placeholder="Search">
            </div>
            <div class="col-lg-6">

                    <a href="#modal-new" class="btn btn-primary" data-toggle="modal">Add New</a>
            </div>
        </div>
        <div class="row">

            <div class="col-lg-10">

                <div class="panel panel-inverse" style="background: none">

                    <div class="panel-body p-10">
                        <div style="background: #fff">
                            <div class="task-header" style="border-bottom: 2px solid #ccc;">
                                <div class="row p-10">
                                    <div class="col-lg-6  f-w-500">
                                        <strong>Milestones Due Soon</strong>
                                    </div>
                                    <div class="col-lg-6 text-right">
                                        <!--<a class=""-->
                                           <!--href="tasks.html">See all my tasks</a>-->
                                    </div>

                                </div>

                            </div>

                            <div>
                            <table class="table m-b-0">
                                <thead>
{#                                <tr>#}
{#                                    <th>Milestone Name</th>#}
{#                                    <th></th>#}
{#                                    <th></th>#}
{#                                </tr>#}
                                </thead>
                                <tbody>
                                {% for milestone in milestones %}
                                 <tr>
                                    <td>{{ milestone.name }}</td>
                                    <td>{{ milestone.assignee.full_name }}</td>
                                    <td>{{ milestone.due_date|naturalday }}</td>
                                </tr>
                                    {% empty %}
                                    <tr><td colspan="3">No milestone for this project</td></tr>
                                {% endfor %}
                                </tbody>
                            </table>
{#                                <ul class="todolist">#}
{#                                    {% for m in milestones %}#}
{#                                    <li>#}
{#                                        <a href="javascript:;" class="todolist-container" data-click="todolist">#}
{#                                            <div class="todolist-input"><i class="fa fa-square"></i></div>#}
{#                                            <div class="todolist-title" style="width: 100%">#}
{#                                                <div class="text-left">#}
{#                                                    Duis pharetra mi sit amet dictum congue.#}
{#                                                </div>#}
{#                                                <div class="text-right">#}
{#                                                    <small>10-15-2019</small>#}
{#                                                </div>#}
{#                                            </div>#}
{#                                        </a>#}
{#                                    </li>#}
{#                                        {% empty %}#}
{#                                        <li> No milestones </li>#}
{#                                    {% endfor %}#}
{#                                </ul>#}
                            </div>
                        </div>
                        <div class="task-header m-t-15" >
                            <div class="row p-10">
                                <div class="col-lg-6  f-w-500">
                                    <strong>Projects</strong>
                                </div>

                            </div>
                            <div class="row">
                                {% for project in projects %}
                                        <div class="col-sm-4">
                                    <div class="card">
                                        <div class="card-block">
                                            <h4 class="card-title">{{ project.name }}</h4>
                                            <h6 class="card-subtitle m-b-10 text-muted">
                                                <span class="m-r-5">Start Date: {{ project.start_date|naturalday }}</span>
                                                <span class="">End Date: {{ project.end_date|naturalday }}</span>
                                            </h6>
                                            <p class="card-text"></p>
                                            <p class="card-text"><small class="text-muted">
                                                {{ project.created_at|naturaltime }}</small></p>
                                            <a href="{% url "projects:milestone" id=project.id %}" class="card-link">Milestones</a>
                                            <a href="{% url "projects:applications" id=project.id %}" class="card-link">Applications</a>
                                        </div>
                                    </div>
                                </div>
                                    {% empty %}
                                    <div class="text-center">No project created</div>
                                {% endfor %}

                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div>
    <div class="modal fade" id="modal-new" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
             <form action="" method="post" enctype="multipart/form-data">
                <div class="modal-header">
                    <h4 class="modal-title">Project Details</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">

                    {%  csrf_token %}
                        <div class="form-group">
                            <label>Name</label>
                            <input class="form-control"
                                   value="{{ form.name.value }}"
                                   name="name"
                                   type="text"/>
                        </div>
                        <div class="form-inline m-b-5">
                            <div class="form-group m-r-5">
                                <label class="m-r-3">Start Date</label>
                                <input class="form-control"
                                        value="{{ form.start_date.value }}"
                                        name="start_date"
                                       type="date"/>
                            </div>
                            <div class="form-group">
                                <label class="m-r-3">End Date</label>
                                <input class="form-control"
                                        value="{{ form.end_date.value }}"
                                        name="end_date"
                                       type="date"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Category</label>
                            <select class="form-control"  value="{{ form.category.value }}"
                                   name="category">
                                <option>--Select Category---</option>
                                <option>Agriculture</option>
                                <option>Infrastructure</option>
                                <option>Green Initiative</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Funding</label>
                            <select class="form-control" multiple  value="{{ form.funding.value }}"
                                   name="funding">
                                <option >--Select Funding---</option>
                                {% for f in funding %}
                                    <option value="{{ f.id }}">{{f.fund_name}}</option>
                                {% endfor %}

                            </select>
                        </div>
                        <div class="form-group">
                            <label>Budget</label>
                            <input class="form-control" value="{{ form.budget.value }}"
                                   name="budget" type="tel"/>
                        </div>

                        <div class="form-group">
                            <label>Description</label>
                            <textarea class="form-control" name="description"> {{ form.description.value }}</textarea>
                        </div>
                        <div>
                            <label>Uploading supporting document </label>
                            <input class="form-control" type="file" name="file">
                        </div>


                </div>
                <div class="modal-footer">
                    <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Close</a>
                    <button type="submit" class="btn btn-success" >Save</button>
                </div>
             </form>
            </div>
        </div>
    </div>
{% endblock %}

{#{% block pagejs %}#}
{##}
{#{% endblock %}#}

projects/templates/projects/milestones.html
{% extends "main/base.html" %}
{% load static %}

{% block pagecss %}
    <link href="../assets/plugins/jquery-jvectormap/jquery-jvectormap.css" rel="stylesheet" />
    <link href="../assets/plugins/bootstrap-datepicker/css/bootstrap-datepicker.css" rel="stylesheet" />
    <link href="../assets/plugins/gritter/css/jquery.gritter.css" rel="stylesheet" />
{% endblock %}

{% block content %}
<div id="content" class="content">
        <!-- begin breadcrumb -->
        <ol class="breadcrumb pull-right">
            <li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
            <li class="breadcrumb-item active">Projects</li>
        </ol>
        <!-- end breadcrumb -->
        <!-- begin page-header -->
        <h1 class="page-header">{{ project.name }} Milestones</h1>
        <!-- end page-header -->
        <div class="row m-b-40" >
            <div class="col-lg-3">
                <input type="email" class="form-control m-b-5" placeholder="Search">
            </div>
            <div class="col-lg-6">

                <a href="#modal-new" class="btn btn-primary" data-toggle="modal">Add Milestone</a>
            </div>
        </div>
        <div class="row">

            <div class="col-lg-10">

                <div class="panel panel-inverse" style="background: none">

                    <div class="panel-body">
                        <div style="background: #fff">
                            <table class="table m-b-0">
                                <thead>
                                <tr>
                                    <th>Milestone Name</th>
                                    <th>Assignee</th>
                                    <th>Due date</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for milestone in milestones %}
                                 <tr>
                                    <td>{{ milestone.name }}</td>
                                    <td>{{ milestone.assignee.full_name }}</td>
                                    <td>{{ milestone.due_date|date:"m-d-Y" }}</td>
                                </tr>
                                    {% empty %}
                                    <tr><td colspan="3">No milestone for this project</td></tr>
                                {% endfor %}
                                </tbody>
                            </table>

                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div>
   <div class="modal fade" id="modal-new" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
            <form action="" method="post" enctype="multipart/form-data">
            {%  csrf_token %}
                <div class="modal-header">
                    <h4 class="modal-title">Milestone Details</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">

                        <div class="form-group">
                            <label>Name</label>
                            <input class="form-control"
                                   value="{{ form.name.value }}"
                                   name="name"
                                   type="text"/>
                        </div>
                        <div class="form-group m-r-5">
                            <label class="m-r-3">Due Date</label>
                            <input class="form-control"
                                   value="{{ form.due_date.value }}"
                                   name="due_date"
                                   type="date"/>
                        </div>
                        <div class="form-group">
                            <label>Assignee</label>
                            <select class="form-control" value="{{ form.assignee.value }}"
                                   name="assignee">
                                <option>--Select User---</option>
                                {% for u in users %}
                                     <option value="{{ u.uuid }}" >{{ u.full_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Set Reminder
                                <small>You will be reminder before the due date</small>
                            </label>
                            <input type="tel" value="{{ form.reminder.value }}"
                                   name="reminder"
                                   class="form-control" placeholder="enter number of days">
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <textarea class="form-control" name="description">{{ form.description.value }}</textarea>
                        </div>
                        <div>
                            <label>Uploading supporting document </label>
                            <input class="form-control" type="file" name="file">
                        </div>


                </div>
                <div class="modal-footer">
                    <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Close</a>
                    <button type="submit" class="btn btn-success" >Save</button>
                </div>
            </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block pagejs %}
<script src="../assets/plugins/gritter/js/jquery.gritter.js"></script>
<script src="../assets/plugins/flot/jquery.flot.min.js"></script>
<script src="../assets/plugins/flot/jquery.flot.time.min.js"></script>
<script src="../assets/plugins/flot/jquery.flot.resize.min.js"></script>
<script src="../assets/plugins/flot/jquery.flot.pie.min.js"></script>
<script src="../assets/plugins/sparkline/jquery.sparkline.js"></script>
<script src="../assets/plugins/jquery-jvectormap/jquery-jvectormap.min.js"></script>
<script src="../assets/plugins/jquery-jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<script src="../assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script src="../assets/js/demo/dashboard.min.js"></script>
<!-- ================== END PAGE LEVEL JS ================== -->

<script>
    $(document).ready(function() {
        App.init();
        Dashboard.init();
    });
</script>
{% endblock %}